layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: rabiibouhestine
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Traveling
    #web_url: https://github.com/topics/css
    image_url: https://www.freeiconspng.com/uploads/travel-icon-png-25.jpg

  - name: Video Games
    #web_url: https://github.com/topics/css  
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Video-Game-Controller-Icon.svg/1024px-Video-Game-Controller-Icon.svg.png
    
  - name: Fitness
    #web_url: https://github.com/topics/sass
    image_url: https://wwfitness.files.wordpress.com/2017/09/fitness-icon-02.png
    
  - name: Movies
    image_url: http://www.salud.gov.pr/Sobre-tu-Salud/PublishingImages/Pages/Condiciones/VIH/video-production.png
