layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: rabiibouhestine
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: My Resume
    web_url: https://rabiibouhestine.github.io/test/
    image_url: https://raw.githubusercontent.com/rabiibouhestine/rabiibouhestine.github.io/master/assets/resumeIcon.png

  - name: My Linkedin
    web_url: https://www.linkedin.com/in/rabiibouhestine
    image_url: https://raw.githubusercontent.com/rabiibouhestine/rabiibouhestine.github.io/master/assets/linkedinIcon.png
    
  - name: My Kaggle
    web_url: https://www.kaggle.com/rabii1992
    image_url: https://raw.githubusercontent.com/rabiibouhestine/rabiibouhestine.github.io/master/assets/kaggleIcon.png
