layout: sidebar.
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

 social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
    linkedin: rabiibouhestine
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
    website: https://rabiibouhestine.github.io/
  # youtube: your_username

topics:
  - name: Deep Learning
    #web_url: https://github.com/topics/css
    image_url: https://mpng.pngfly.com/20181203/ceh/kisspng-machine-learning-artificial-intelligence-marketing-5c04cf29d82e13.2625508415438190498855.jpg
    
  - name: AI
    #web_url: https://github.com/topics/css
    image_url: https://www.cisco.com/c/en/us/solutions/artificial-intelligence/_jcr_content/Grid/category_atl_d424/layout-category-atl/blade_e87d/bladeContents/spotlight_def3/image.img.png/1559848079283.png
    
  - name: Crypto Currency
    #web_url: https://github.com/topics/css
    image_url: https://upload.wikimedia.org/wikipedia/commons/8/8b/Cryptocurrency_Logo.svg

